name: Javascript Build & Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Build & Test
      run: npm install
    # - name: Build & Test
    #   run: |
    #     npm run build && npm run jstest
